name: SSH Setup and Test Connection

on:
  push:
    branches:
      - main  # Of een andere branch waarop je de workflow wilt uitvoeren

jobs:
  ssh-setup:
    runs-on: ubuntu-latest  # Dit draait de job op een GitHub Actions runner met Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          echo "Creating .ssh directory"
          mkdir -p $HOME/.ssh
          echo "Adding server to known_hosts"
          ssh-keyscan -p 65002 89.117.228.91 >> $HOME/.ssh/known_hosts
          echo "Host key added successfully"
          chmod 644 $HOME/.ssh/known_hosts
          echo "Permissions updated"
          ls -al $HOME/.ssh  # Controleer de inhoud van de .ssh directory
          echo "Done with SSH setup"

      - name: Add SSH private key to the agent
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "SSH private key added"

      - name: Configure SSH settings
        run: |
          echo "Host *" > ~/.ssh/config
          echo "  Port 65002" >> ~/.ssh/config
          echo "  User u503411290" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "SSH config updated"

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -p 65002 u503411290@89.117.228.91 "echo 'SSH connection successful'"

      - name: Done
        run: echo "SSH setup complete and connection test passed"