name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # Zorg ervoor dat dit overeenkomt met de branch die je wilt deployen

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Stap 1: Checkout de code uit je GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Stap 2: Stel de SSH-configuratie in en voeg de host toe aan known_hosts
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Zorg ervoor dat je private key in GitHub secrets staat

      # Stap 3: Voeg de SSH-host toe aan known_hosts
      - name: Add SSH host to known_hosts
        run: |
          echo "Creating .ssh directory"
          mkdir -p $HOME/.ssh
          echo "Adding host key"
          ssh-keyscan -t rsa 89.117.228.91 >> $HOME/.ssh/known_hosts || { echo "Failed to run ssh-keyscan"; exit 1; }
          echo "Host key added successfully"
          cat $HOME/.ssh/known_hosts  # Bekijk het bestand om te controleren
          chmod 644 $HOME/.ssh/known_hosts || { echo "Failed to change permissions"; exit 1; }
          echo "Permissions updated"
          ls -al $HOME/.ssh  # Controleer de inhoud van de .ssh directory
          echo "Done with SSH setup"

      # Stap 4: Test SSH-verbinding
      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -p 65002 u503411290@89.117.228.91 "echo 'SSH connection successful'"
          echo "SSH connection test passed"

      # Stap 5: Voer een simpel commando uit op de server via SSH om te testen
      - name: Run command on Hostinger
        run: |
          ssh -o StrictHostKeyChecking=no -p 65002 u503411290@89.117.228.91 "hostname && date"
          echo "Command execution on server complete"