name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # Dit kan een andere branch zijn, afhankelijk van je setup

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "Creating .ssh directory"
          mkdir -p $HOME/.ssh
          echo "Adding host key"
          ssh-keyscan -t rsa 89.117.228.91 >> $HOME/.ssh/known_hosts
          echo "Host key added successfully"
          chmod 644 $HOME/.ssh/known_hosts
          ls -al $HOME/.ssh
        env:
          SSH_AUTH_SOCK: /tmp/ssh-XXXXXXk5kYYc/agent.1780
          SSH_AGENT_PID: 1781

      - name: Deploy to Hostinger using rsync
        run: |
          echo "Deploying files to Hostinger server"
          rsync -avz --delete --exclude='.git*' ./ u503411290@89.117.228.91:/pad/naar/de/doelmap/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Verify deployment
        run: |
          echo "Verifying deployment on server"
          ssh -o StrictHostKeyChecking=no -p 65002 u503411290@89.117.228.91 "echo 'Deployment successful'"